import { scoreProfile, describeScore, validateProfile } from '../profile/validate.js';
import { suggestTheme, listThemes } from '../themes/index.js';
import { formatAddress } from '../profile/normalize.js';
import { truncate } from '../util/text.js';

const bullet = (items, empty = '_none found_') =>
  items.length ? items.map((i) => `- ${i}`).join('\n') : empty;

/**
 * The enrichment brief: a self-contained prompt for a Claude Code session that
 * turns harvested source material into finished marketing copy.
 *
 * It is deliberately explicit about what may not be invented. Fabricated
 * reviews, licences or prices are a legal problem for the business you are
 * selling this site to, not just a quality one.
 */
export function renderBrief(raw, draft, { clientSlug } = {}) {
  const score = scoreProfile(draft);
  const validation = validateProfile(draft);
  const suggestion = suggestTheme(draft);
  const slug = clientSlug || draft.slug;

  const homePage = raw?.pages?.find((p) => p.kind === 'home') ?? raw?.pages?.[0] ?? {};
  const sourceParagraphs = (raw?.pages ?? []).flatMap((p) =>
    (p.paragraphs ?? []).map((text) => ({ page: p.kind, text })),
  );

  const L = [];

  L.push(`# Enrichment brief — ${draft.business.name || slug}`);
  L.push('');
  L.push(`> Generated by \`avo brief ${slug}\`. Run this in a Claude Code session, then \`avo build ${slug}\`.`);
  L.push('');

  L.push('## Your task');
  L.push('');
  L.push(`Read the harvested material below and write **\`clients/${slug}/profile.json\`** — a complete, polished business profile that \`avo build\` will turn into a modern website.`);
  L.push('');
  L.push(`Start from \`clients/${slug}/profile.draft.json\` (already generated, ${score.percent}% complete). The draft contains copy lifted verbatim from the old site. Your job is to **rewrite it properly**, fill the gaps you legitimately can, and flag the ones you cannot.`);
  L.push('');

  L.push('### Rules — read these first');
  L.push('');
  L.push('These matter because a real business will publish this and be judged on it.');
  L.push('');
  L.push('| Never | Why |');
  L.push('| --- | --- |');
  L.push('| Invent a testimonial, review, rating or customer name | Fabricated reviews are illegal in most jurisdictions (FTC in the US, CMA in the UK). Only use quotes that appear in the harvested data. |');
  L.push('| Invent licence numbers, certifications, insurance or accreditations | Claiming credentials a business does not hold exposes them to real liability. |');
  L.push('| Invent prices, guarantees, warranties or response times | These are contractual promises. If it is not in the source, leave it out. |');
  L.push('| Invent years in business, staff counts or job numbers | "Serving since 1987" must come from the source, not from a nice round number. |');
  L.push('| Invent an address, service area or phone number | Wrong contact details lose leads and break local SEO. |');
  L.push('');
  L.push('Anything you would like to claim but cannot verify goes in `_meta.todo` as a question for the business owner. That list becomes your client kick-off call.');
  L.push('');
  L.push('**Do** rewrite freely for tone, clarity, structure and length. Turning "WELCOME TO OUR WEBSITE" into a benefit-led headline is the entire point of this step.');
  L.push('');

  L.push('## The business at a glance');
  L.push('');
  L.push('| Field | Harvested value |');
  L.push('| --- | --- |');
  L.push(`| Name | ${draft.business.name || '❓'} |`);
  L.push(`| Category | ${draft.business.category || '❓ — infer it from the services and set it; it drives the schema.org type'} |`);
  L.push(`| Phone | ${draft.contact.phone || '❓'} |`);
  L.push(`| Email | ${draft.contact.email || '❓'} |`);
  L.push(`| Address | ${formatAddress(draft.contact.address) || '❓'} |`);
  L.push(`| Service area | ${draft.business.serviceArea.join(', ') || '❓ — check the old site copy for town names'} |`);
  L.push(`| Founded | ${draft.business.founded || '❓'} |`);
  L.push(`| Old site | ${raw?.startUrl ?? '—'} (${raw?.audit?.platform || 'unknown platform'}) |`);
  L.push('');

  L.push('## Recommended theme');
  L.push('');
  L.push(`\`${suggestion.theme}\`${suggestion.confident ? '' : ' _(low confidence — pick a better fit if you can see one)_'}`);
  L.push('');
  L.push('| Theme | Suits |');
  L.push('| --- | --- |');
  for (const t of listThemes()) L.push(`| \`${t.id}\` — ${t.name} | ${t.bestFor.slice(0, 5).join(', ')} |`);
  L.push('');
  L.push('Set your choice in `site.theme`.');
  L.push('');

  L.push('## What to write');
  L.push('');
  L.push('### 1. Hero');
  L.push('');
  L.push(`Current headline: **${draft.content.hero.headline || '_none_'}**`);
  L.push('');
  L.push('Write `content.hero.headline` as a benefit the customer cares about, not a greeting. Ten words maximum. Then `content.hero.subhead`: one or two sentences naming what they do, who for, and where.');
  L.push('');
  L.push('Also set `content.hero.primaryCta` (`{ "label": "...", "href": "contact/" }`) — say what happens, e.g. "Get a free estimate", not "Submit".');
  L.push('');

  L.push('### 2. Value propositions');
  L.push('');
  L.push('Write three or four `content.valueProps` entries (`{ icon, title, text }`) — the reasons to choose this business over the competitor down the road. Base them on evidence in the source material.');
  L.push('');
  L.push('Available `icon` values: `checkCircle`, `shield`, `clock`, `award`, `users`, `wrench`, `sparkle`, `star`, `calendar`, `phone`, `pin`.');
  L.push('');
  if (draft.business.founded) {
    L.push(`The source says they were founded in ${draft.business.founded}, so "${new Date().getFullYear() - Number(draft.business.founded)}+ years in business" is fair game as a stat.`);
    L.push('');
  }

  L.push('### 3. Services');
  L.push('');
  L.push(`${draft.services.length} service(s) harvested. For each: keep the real name, write a \`summary\` of 15–30 words, and a \`description\` array of 2–4 paragraphs for its own page.`);
  L.push('');
  if (draft.services.length) {
    L.push('```');
    for (const s of draft.services) {
      L.push(`${s.name}`);
      L.push(`  summary: ${s.summary || '(none — write one)'}`);
    }
    L.push('```');
    L.push('');
  }

  L.push('### 4. About');
  L.push('');
  L.push('Rewrite `content.about.body` as 2–4 paragraphs. Keep every verifiable fact from the source; drop the filler. Add `content.about.highlights` (short proof points) if the source supports them.');
  L.push('');

  L.push('### 5. SEO');
  L.push('');
  L.push('`seo.title` under 60 characters including the town. `seo.description` 140–160 characters, active voice, with a reason to click.');
  L.push('');

  L.push('## Harvested source material');
  L.push('');
  L.push('Everything below came off the existing site. Treat it as raw material, not as copy to keep.');
  L.push('');

  L.push('<details><summary>Page copy</summary>');
  L.push('');
  for (const page of (raw?.pages ?? [])) {
    L.push(`#### ${page.kind} — ${page.url}`);
    L.push('');
    if (page.title) L.push(`*Title:* ${page.title}`);
    if (page.description) L.push(`*Meta:* ${page.description}`);
    L.push('');
    if (page.headings?.length) {
      L.push('Headings:');
      L.push(bullet(page.headings.map((h) => `\`h${h.level}\` ${h.text}`)));
      L.push('');
    }
    if (page.paragraphs?.length) {
      L.push('Copy:');
      L.push('');
      for (const p of page.paragraphs.slice(0, 12)) L.push(`> ${p}`);
      L.push('');
    }
  }
  L.push('</details>');
  L.push('');

  if (draft.testimonials.length) {
    L.push('### Testimonials found (use verbatim — do not embellish)');
    L.push('');
    for (const t of draft.testimonials) {
      L.push(`> ${t.quote}`);
      L.push(`> — ${t.author || '_no name given_'}${t.location ? `, ${t.location}` : ''}${t.rating ? ` (${t.rating}★)` : ''}`);
      L.push('');
    }
  }

  if (draft.faqs.length) {
    L.push('### FAQs found');
    L.push('');
    for (const f of draft.faqs) L.push(`- **${f.question}** ${truncate(f.answer, 160)}`);
    L.push('');
  }

  if (raw?.social?.profiles?.length) {
    L.push('### Social profiles');
    L.push('');
    L.push('| Network | Status | What to do |');
    L.push('| --- | --- | --- |');
    for (const p of raw.social.profiles) {
      const action = p.status === 'ok'
        ? `Readable — mine the bio for tone: "${truncate(p.data?.description ?? '', 90)}"`
        : 'Blocked to anonymous requests. Add to `_meta.todo` and ask the client.';
      L.push(`| ${p.label} | ${p.status} | ${action} |`);
    }
    L.push('');
  }

  if (raw?.assets?.length) {
    L.push('### Images downloaded');
    L.push('');
    L.push('Reference these by their `assets/harvested/...` path. Write real alt text for every one.');
    L.push('');
    for (const a of raw.assets) L.push(`- \`${a.file}\` (${a.role})${a.alt ? ` — alt on old site: "${a.alt}"` : ' — **no alt text on the old site, write one**'}`);
    L.push('');
  }

  L.push('## Gaps to close');
  L.push('');
  L.push('```');
  L.push(describeScore(score));
  L.push('```');
  L.push('');
  L.push('| Missing field | Weight | Note |');
  L.push('| --- | --- | --- |');
  for (const gap of score.missing.slice(0, 14)) {
    L.push(`| \`${gap.path}\` | ${gap.weight} | ${gap.hint || (gap.required ? '**Required to build.**' : '')} |`);
  }
  L.push('');
  if (validation.warnings.length) {
    L.push('Quality warnings on the draft:');
    L.push('');
    L.push(bullet(validation.warnings));
    L.push('');
  }

  L.push('## Output contract');
  L.push('');
  L.push(`Write \`clients/${slug}/profile.json\`. It must:`);
  L.push('');
  L.push('1. Keep the same shape as `profile.draft.json` (same keys, same nesting).');
  L.push('2. Set `_meta.enriched` to `true`.');
  L.push('3. List every unverifiable claim you left out in `_meta.todo`, phrased as a question for the owner.');
  L.push('4. Set `site.theme`, and `site.domain` if you know the new domain.');
  L.push('');
  L.push('Then verify:');
  L.push('');
  L.push('```bash');
  L.push(`avo check ${slug}      # validation + completeness score`);
  L.push(`avo build ${slug}      # writes clients/${slug}/dist/`);
  L.push(`avo preview ${slug}    # local preview with a theme switcher`);
  L.push('```');
  L.push('');

  return L.join('\n');
}
